version: 2.1

workflows:
    build-test:
        jobs:
          - build:
              # https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-context
              context: secrets
jobs:
    build:
        docker:
            - image: cimg/go:1.13
              environment:
                  TAG: "0.0.0"
        steps:
            - checkout
            - setup_remote_docker
            # build and push Docker image
            - run: |
                docker build -t peterskipper/python-example-repository:$TAG .
                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                docker push peterskipper/python-example-repository:$TAG

